on: push
jobs:
  deploy-home:
    if: github.ref == 'refs/heads/main'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: |
          pnpm -F home install --frozen-lockfile
          pnpm -F home build
          pnpm -F home exec aws s3 sync dist s3://cruftbusters.com
          aws cloudfront create-invalidation --distribution-id E3P0VPLWYNJVFR --paths /
